name: sitemap-generate
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install -g sitemap-generator-cli
          sitemap-generator https://ai.masyumaroking.com/ -l -f ./docs/sitemap.xml
          git config user.name  "github-action"
          git config user.email "github-action@example.com"
          git add ./docs
          git commit -m "sitemap update"
          git pull
          git push